### PR TITLE
standardise on scalatest 3.2.14

### PR DESCRIPTION
**Pull request by pjfanning**
matches what is used in pekko core

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by He-Pin** [comment]
oops, it's two commits

**Comment by pjfanning** [comment]
I always Squash Merge - which takes all the commits in the PR and makes one commit on the destination branch. This Rebase Merge should be ok. The branch is protected making it difficult to undo this. It's probably best to leave it unless it causes trouble.

**Comment by He-Pin** [comment]
yeah, i missed it have two commits😓😓😓

**Pull request merged**
