### PR TITLE
Add withClientId to ProducerSettings

### PR DESCRIPTION
**Pull request by dragisak**
This is the same as https://github.com/akka/alpakka-kafka/pull/1470

### CODE REVIEW

**Comment by pjfanning** [comment]
@mdedetrich seems ok to me - even for 1.0.0 - wdyt?

**Comment by dragisak** [comment]
This is adding parity with [ConsumerSettings.withClientId](https://github.com/apache/incubator-pekko-connectors-kafka/blob/main/core/src/main/scala/org/apache/pekko/kafka/ConsumerSettings.scala#L280)

**Comment by mdedetrich** [comment]
According to CI this method already exists? https://github.com/apache/incubator-pekko-connectors-kafka/actions/runs/5548446654/jobs/10131476588?pr=108 ?

```
[error] /home/runner/work/incubator-pekko-connectors-kafka/incubator-pekko-connectors-kafka/core/src/main/scala/org/apache/pekko/kafka/ProducerSettings.scala:249:7: method withClientId is defined twice;
[error]   the conflicting method withClientId was defined at line 242:7
[error]   def withClientId(clientId: String): ProducerSettings[K, V] =
```

at https://github.com/apache/incubator-pekko-connectors-kafka/blob/1a7434f4af829b13ecdc4459850a3df41cc3fb43/core/src/main/scala/org/apache/pekko/kafka/ProducerSettings.scala#L242-L243

**Comment by pjfanning** [comment]
I mistook the date of the [alpakka merge](https://github.com/akka/alpakka-kafka/pull/1470) - it was Feb 2022. I assumed it was 2023.

The code in incubator-pekko-connectors-kafka was forked in Sept 2023 so everything merged before Sept 2023 is in this pekko fork already.

**Comment by dragisak** [comment]
Ha. I created this PR because my Akka code change didn't make into the release. Closing this then

**Pull request closed without merging**
