### PR TITLE
Add sbt-license-report

### PR DESCRIPTION
**Pull request by mdedetrich**
Adds license report

### CODE REVIEW

**Comment by pjfanning** [comment]
We have 3 choices about the 1.0.0 docs for pekko-connectors-kafka:
1. merge this and generate the 1.0.0 docs with this change - which will have a slightly incorrect report about rs-api jar
2. merge this but set up the 1.0 doc publish job to use the git ref with the 1.0.0 git tag when generating the 1.0.0 docs
3. delay merging this until after we generate the 1.0.0 docs

**Comment by mdedetrich** [comment]
> We have 3 choices about the 1.0.0 docs for pekko-connectors-kafka:
> 
> 1. merge this and generate the 1.0.0 docs with this change - which will have a slightly incorrect report about rs-api jar
> 2. merge this but set up the 1.0 doc publish job to use the git ref with the 1.0.0 git tag when generating the 1.0.0 docs
> 3. delay merging this until after we generate the 1.0.0 docs

Well I would say that we have 2 choices, choice 3 doesn't give us buy as anything (as you said we can always just make sure the job uses git ref when publishing docs, this is a non issue). If https://github.com/apache/incubator-pekko-connectors-kafka/pull/116 wasn't merged then there might have a slight case of not merging this PR, but alas thats not the case.

**Review by pjfanning — APPROVED** [review]
lgtm

Let's worry about the 1.0.0 docs when we get around to generating them.

**Comment by mdedetrich** [comment]
Ill leave this open for now incase we do get some issues using a git ref (not expecting any problems here), no hurry to merge either way.

**Comment by pjfanning** [comment]
The incubator-pekko 1.0 publish job uses a git ref in its checkout and it works fine.

**Comment by pjfanning** [comment]
> @pjfanning So the vote for this project passed, what are your thoughts on this?

* The new 1.0.0 jars should be built off the commit that was voted on so merging this does not affect that.
* We don't yet have 1.0.0 docs published. We could choose to build those from the same commit as we voted on or we could build them based on latest commits (including this). I think it isn't a big deal if the license report is slightly incorrect (rs-api jar has been upgraded since the vote was called).

**Pull request merged**
