### PR TITLE
Update to SBT 1.9.6 and use Apache Staging repo constant

### PR DESCRIPTION
**Pull request by mdedetrich**
SBT 1.9.5. added the `Resolver.ApacheMavenStagingRepo` constant

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
Could we hold off on merging more of these sbt upgrades while the incubator-pekko compile issue is investigated?

**Comment by mdedetrich** [comment]
> Could we hold off on merging more of these sbt upgrades while the incubator-pekko compile issue is investigated?

Solved with sbt 1.9.6

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
